#+TITLE: Pip Boy Emacs Configurations

* Table of Contents :TOC_3:
- [[#preamble][Preamble]]
  - [[#emacs-lisp-scripts][Emacs Lisp Scripts]]
  - [[#personal-information][Personal Information]]
- [[#os][OS]]
  - [[#mac-os][Mac OS]]
    - [[#set----keys][Set ⌘ ⌥ ⌃ Keys]]
- [[#ui][UI]]
  - [[#splash-image][Splash Image]]
  - [[#main-theme][Main Theme]]
  - [[#mouse-cursor-color][Mouse Cursor Color]]
  - [[#evil-cursor-state-colors][Evil Cursor State Colors]]
  - [[#menue-bar][Menue Bar]]
  - [[#modeline][Modeline]]
    - [[#configure-doom-modeline][Configure doom-modeline]]
    - [[#show-battery-usage][Show battery usage]]
    - [[#disable-buffer-size][Disable buffer size]]
  - [[#treemacs][Treemacs]]
  - [[#editor][Editor]]
    - [[#line-numbers][Line Numbers]]
    - [[#fill-column][fill-column]]
  - [[#font][Font]]
- [[#terminal][Terminal]]
  - [[#tmux][tmux]]
    - [[#key-bindings][Key Bindings]]
  - [[#vterm][vterm]]
- [[#tramp][Tramp]]
- [[#spell-checker][Spell Checker]]
- [[#dired][dired]]
- [[#projectile][Projectile]]
- [[#dash-api-browser][Dash API Browser]]
- [[#org][Org]]
  - [[#aesthetics][Aesthetics]]
  - [[#inline-latex-fragment][Inline Latex Fragment]]
  - [[#key-maps][Key Maps]]
  - [[#directory-structure][Directory Structure]]
  - [[#get-things-done][Get Things Done]]
    - [[#files][Files]]
    - [[#state-keywords][State Keywords]]
    - [[#tags][Tags]]
    - [[#org-agenda][org-agenda]]
    - [[#org-refile][org-refile]]
    - [[#org-capture][org-capture]]
    - [[#org-archive][org archive]]
  - [[#zettelkasten][Zettelkasten]]
    - [[#org-roam][org-roam]]
    - [[#org-ref][org-ref]]
    - [[#helm-bibtex--ivy-bibtex][helm-bibtex & ivy-bibtex]]
    - [[#org-noter][org-noter]]
    - [[#org-roam-bibtex][org-roam-bibtex]]
    - [[#deft][deft]]
  - [[#enable-minor-modes][Enable minor modes]]
  - [[#cv--resume][CV & Resume]]
    - [[#org-export-functions][org-export functions]]
    - [[#keybindings][Keybindings]]
    - [[#export-backends][Export Backends]]
  - [[#org-export][org-export]]
    - [[#latex][LaTex]]
  - [[#org-babel][org-babel]]
    - [[#prolog][Prolog]]
  - [[#org-drill][org-drill]]
- [[#latex-1][LaTeX]]
- [[#flycheck][Flycheck]]
- [[#languages][Languages]]
  - [[#lsp][LSP]]
    - [[#configuration][Configuration]]
    - [[#autocompletion][Autocompletion]]
    - [[#lsp-ui-configurations][LSP UI Configurations]]
  - [[#dap][DAP]]
    - [[#ui-1][UI]]
    - [[#python][Python]]
    - [[#keybindings-1][Keybindings]]
  - [[#python-1][Python]]
    - [[#editor-1][Editor]]
    - [[#debugger][Debugger]]
    - [[#repl][REPL]]
    - [[#poetry][Poetry]]
    - [[#pyright-language-server][Pyright Language Server]]
    - [[#sphinx-doc][~sphinx-doc~]]
  - [[#prolog-1][Prolog]]
    - [[#ediprolog][~ediprolog~]]
  - [[#scala][Scala]]
- [[#ai--assistant][AI & Assistant]]
  - [[#llm][LLM]]
  - [[#claude-code-ide][Claude Code IDE]]
  - [[#copilot][Copilot]]

* Preamble
** Emacs Lisp Scripts
If you have file A, that calls load to load a file at B, and B calls load on
file C using a relative path, then Emacs will complain about unable to find C.
Because, emacs does not switch current directory with load.

The following function solves this problem.
#+begin_src emacs-lisp
;;; -*- lexical-binding: t; -*-
(defun leo-get-fullpath (@file-relative-path)
  "Return the full path of *file-relative-path, relative to caller's file location.

Example: If you have this line
 (xah-get-fullpath \"../xyz.el\")
in the file at
 /home/joe/emacs/emacs_lib.el
then the return value is
 /home/joe/xyz.el
Regardless how or where emacs_lib.el is called.

This function solves 2 problems.

① If you have file A, that calls the `load' on a file at B, and B calls `load' on file C using a relative path, then Emacs will complain about unable to find C. Because, emacs does not switch current directory with `load'.

To solve this problem, when your code only knows the relative path of another file C, you can use the variable `load-file-name' to get the current file's full path, then use that with the relative path to get a full path of the file you are interested.

② To know the current file's full path, emacs has 2 ways: `load-file-name' and `buffer-file-name'. If the file is loaded by `load', then `load-file-name' works but `buffer-file-name' doesn't. If the file is called by `eval-buffer', then `load-file-name' is nil. You want to be able to get the current file's full path regardless the file is run by `load' or interactively by `eval-buffer'."

  (concat (file-name-directory (or load-file-name buffer-file-name)) @file-relative-path))
#+end_src
** Personal Information
+ Username comes from the environment.
+ Set the email address to my Gmail address.
  #+begin_src emacs-lisp
  (setopt user-mail-address "ashkan.aleali@gmail.com")
  #+end_src
** Files
Disable lockfiles (causes noise in version-controlled dirs) and redirect backups
and auto-saves to the system temp directory.
#+begin_src emacs-lisp
(setq create-lockfiles nil)
(setq backup-directory-alist `((".*" . ,temporary-file-directory))
      auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))
#+end_src

* OS
** Mac OS
*** Set ⌘ ⌥ ⌃ Keys
Set command, option, and alt key for both the left and the right part of the
keyboard.
#+BEGIN_SRC emacs-lisp
(setopt mac-option-modifier 'meta
       mac-right-option-modifier 'meta
       mac-command-modifier 'super
       mac-right-command-modifier 'super)
#+END_SRC
* UI
** Splash Image
Because it's a Pip Boy Emacs ;) 
#+begin_src emacs-lisp
(setopt fancy-splash-image (expand-file-name "splash/pipboy.png" doom-private-dir))
#+end_src
** Main Theme
I'm obsessed with the dark solarized theme, but it looks blue in my terminal. So
I use zenburn if I'm in the terminal.

#+begin_src emacs-lisp
(setopt doom-theme (if (display-graphic-p) 'doom-solarized-dark-high-contrast 'doom-monokai-ristretto))
(custom-set-faces '(default ((t (:background unspecified)))))
#+end_src
** Mouse Cursor Color
#+begin_src emacs-lisp
(set-mouse-color "red")
#+end_src
** Evil Cursor State Colors
Set the cursor colors in vi editing mode.
#+begin_src emacs-lisp
(setopt evil-default-cursor '("DodgerBlue1" box)
       evil-normal-state-cursor  '("gray" box)
       evil-emacs-state-cursor   '("orange" box)
       evil-motion-state-cursor  '("SeaGreen1" box)
       evil-insert-state-cursor  '("white" bar)
       evil-visual-state-cursor  '("white" hbar)
       evil-replace-state-cursor '("pink" hbar))
#+end_src
** Menue Bar
#+begin_src emacs-lisp
(menu-bar-mode nil)
#+end_src
** Modeline
*** Configure doom-modeline
#+BEGIN_SRC emacs-lisp
(setopt doom-modeline-icon (display-graphic-p)
       doom-modeline-major-mode-icon t
       doom-modeline-hud t
       doom-modeline-lsp t
       doom-modeline-buffer-file-name-style 'truncate-with-project
       doom-modeline-buffer-encoding nil)
#+END_SRC
*** Show battery usage
Ignore any error here. If running on a PC or server there is no battery status
to show.
#+BEGIN_SRC emacs-lisp
(ignore-errors (display-battery-mode))
#+END_SRC
*** Disable buffer size
Who cares how many bytes this file has?
#+BEGIN_SRC emacs-lisp
(setopt size-indication-mode nil)
#+END_SRC
** Treemacs
+ Use the colorful treemacs theme and doom additions
   #+BEGIN_SRC emacs-lisp
   (setopt doom-themes-treemacs-theme "doom-colors")
   (after! doom-themes (doom-themes-treemacs-config))
   #+END_SRC
+ hide files ignored by Git from treemacs
  #+BEGIN_SRC emacs-lisp
  (after! treemacs
    (add-to-list 'treemacs-pre-file-insert-predicates #'treemacs-is-file-git-ignored?))
  #+END_SRC
** Editor
*** Line Numbers
Disabled globally — line numbers cause slowdown with LSP and break variable-pitch fonts.

#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type nil)
#+END_SRC
** Font
+ Use IntelliJ fonts everywhere. They look gorgeous
+ Use =Chalkboard= as variable pitch font. It looks gorgeous.
#+BEGIN_SRC emacs-lisp
(setopt doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 12)
       doom-unicode-font (font-spec :family "JetBrainsMono Nerd Font" :size 13)
       doom-variable-pitch-font (font-spec :family "Chalkboard" :size 12)
       ivy-posframe-font (font-spec :family "JetBrains Mono Nerd Font" :size 13))
#+END_SRC
* Terminal
** tmux
*** Key Bindings
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("t" . "tmux")
        :desc "cd to buffer dir in active tmux session" "c" #'+tmux/cd
        :desc "cd to project dir in active tmux session" "p" #'+tmux/cd-to-project
        :desc "cd to highlighted region in active tmux session" "C" #'+tmux:cd-here
        :desc "run highlighted region as comand in active tmux session" "x" #'+tmux:run
        :desc "run command in active tmux session" "t" #'+tmux/run
        :desc "re-run the last command in active tmux session" "r" #'+tmux/rerun)))
#+END_SRC
** vterm
+ Set =fish= to be the default shell.
  #+BEGIN_SRC emacs-lisp
  (setopt vterm-shell "fish")
  #+END_SRC
* Tramp
From the [[https://www.gnu.org/software/emacs/manual/html_node/tramp/Frequently-Asked-Questions.html][tramp FAQ page]]:
#+begin_src emacs-lisp
(setq remote-file-name-inhibit-cache nil)
(setq vc-ignore-dir-regexp
      (format "%s\\|%s"
                    vc-ignore-dir-regexp
                    tramp-file-name-regexp))
(setq tramp-verbose 1)

#+end_src
* Spell Checker
+ set personal ~ispell~ dictionary.
  #+begin_src emacs-lisp
  (setopt ispell-personal-dictionary "~/Dropbox/Apps/ispell/english.pws")
  #+end_src
* dired
+ Enable the DWIM (/Do What I Mean/) mode, which makes life much easier when
  moving stuff around in the ~dired~ mode.

#+BEGIN_SRC emacs-lisp
(setopt dired-dwim-target t)
#+END_SRC
* Projectile
+ Set projectile search path to add new projects.
  #+BEGIN_SRC emacs-lisp
  (setopt projectile-project-search-path '("~/w"))
  #+END_SRC
* Dash API Browser
Search Dash GUI from Emacs. Pretty handy! It only works in MacOS.
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("d" . "dash")
        :desc "dash at point" "d" #'dash-at-point
        :desc "dash at point with docset" "a" #'dash-at-point-with-docset)))
#+END_SRC
* Org
I use Org for GTD, Zettelkasten workflows, and as a replacement for markdown and
LaTeX whenever possible.
** Aesthetics
Configure the aesthetics of the org-mode buffer.
#+BEGIN_SRC emacs-lisp
(setopt org-hide-emphasis-markers t
       org-fontify-done-headline t
       org-fontify-whole-heading-line t
       org-fontify-todo-headline t
       org-fontify-emphasized-text t
       org-fontify-quote-and-verse-blocks t)
#+END_SRC
** Inline Latex Fragment
Use [[https://github.com/io12/org-fragtog][org-fragtog]] to enable auto preview of latex fragments.
#+begin_src emacs-lisp
(use-package! org-fragtog
  :after org
  :hook (org-mode . org-fragtog-mode)
  )
#+end_src
** Key Maps
#+BEGIN_SRC emacs-lisp
(after! org
  (map! :map org-mode-map
        :n "M-j" #'org-metadown
        :n "M-k" #'org-metaup
        :n  )
  (map! :leader
        (:prefix-map ("a" . "applications")
         (:prefix ("o" . "org-mode")
          :desc "helm-bibtex" "h" #'helm-bibtex))))
#+END_SRC
** Directory Structure
These paths are usually synced through a cloud provided or a git service. These
paths include the followings:
+ org-roam and org-mode notes files.
+ Bibliography files generated by Zotero.
+ GTD workflow files.
#+BEGIN_SRC emacs-lisp
(setopt pipboy/org-notes (expand-file-name "~/w/roam/")
       pipboy/bibtex-files (directory-files "~/Dropbox/Apps/bibliography/bib/" 'full ".bib")
       pipboy/pdf-directory (expand-file-name "~/Dropbox/Apps/bibliography/pdf/")
       pipboy/gtd-directory (expand-file-name "~/w//beorg"))
#+END_SRC
** Get Things Done
*** Files
Here I set the files to be used by agenda and other task management
functionalities of the org-mode. I follow the GTD workflow.
1) I quick capture my tasks to my inbox.
2) I use the gtd file to organize my projects.
3) I use someday to backlog the tasks I don't wish to complete in the short
   term.
#+BEGIN_SRC emacs-lisp
(setopt org-inbox-file-name (expand-file-name "inbox.org" pipboy/gtd-directory) ;; TODO
       org-tickler-file-name (expand-file-name "tickler.org" pipboy/gtd-directory) ;; TODO
       org-someday-file-name (expand-file-name "someday.org" pipboy/gtd-directory) ;; TODO
       org-gtd-file-name (expand-file-name "gtd.org" pipboy/gtd-directory) ;; TODO

       org-notes-file-name (expand-file-name "notes.org" pipboy/gtd-directory) )
#+END_SRC
*** State Keywords
Set both the keywords and the face of GTD workflow.
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-todo-keywords '((sequence "TODO(t)" "NOW(z)" "NEXT(n)" "WAIT(w)" "SOMEDAY(s) HOLD(h)" "PROJECT(p)"
                                       "|" "DONE(d)" "CANCEL(c)")
                             (sequence "[ ](T)" "[?](W)" "[-](N)"
                                       "|" "[X](x)"))

         org-todo-keyword-faces '(("NOW" . (:foreground "magenta" :weight "bold"))
                                  ("NEXT" . (:foreground "violet" :weight "bold"))
                                  ("WAIT" . +org-todo-onhold)
                                  ("HOLD" . +org-todo-onhold)
                                  ("SOMEDAY" . +org-todo-onhold)
                                  ("PROJECT". +org-todo-project)
                                  ("ABORT" . (+org-todo-inactive))
                                  ("[-]" . +org-todo-active)
                                  ("[?]" . +org-todo-onhold))))
#+END_SRC
*** Tags
These are the tags that I use with my task management workflow.
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-tag-alist '((:startgroup . nil)
                         ("@work" . ?w)
                         ("@home" . ?h)
                         ("@business" . ?b)
                         ("@university" . ?u)
                         ("@travel" . ?t)
                         (:endgroup)

                         (:startgroup . nil)
                         ("@errand". ?r)
                         ("@phone" . ?p)
                         ("@email" . ?e)
                         (:endgroup . nil)

                         (:startgroup . nil)
                         ("emacs")
                         ("tools")
                         ("server")
                         (:endgroup . nil)

                         (:startgroup . nil)
                         ("read")
                         ("write")
                         ("study")
                         ("implement")
                         ("research")
                         (:endgroup . nil)

                         (:startgroup . nil)
                         ("TOC_1" . ?1)
                         ("TOC_2" . ?2)
                         ("TOC_3" . ?3)
                         ("TOC_4" . ?4)
                         (:endgroup . nil))))
#+END_SRC
*** org-agenda
**** Files
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-agenda-files (list pipboy/gtd-directory)
         org-agenda-show-inherited-tags t
         org-default-notes-file org-inbox-file-name))
#+END_SRC
**** org-super-agenda
#+BEGIN_SRC emacs-lisp
(use-package! org-super-agenda
  :defer
  :after (org org-mode org-super-agenda)
  :commands (org-super-agenda-mode))

(after! org-agenda
  (org-super-agenda-mode))
#+END_SRC
**** Agenda View
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-agenda-skip-scheduled-if-done t
         org-agenda-skip-deadline-if-done t
         org-agenda-include-deadlines t
         org-agenda-block-separator nil
         org-agenda-tags-column 100 ;; from testing this seems to be a good value
         org-agenda-compact-blocks t)

  (setopt org-agenda-custom-commands
         '(("o" "Overview"
            ((agenda "" ((org-agenda-span 'day)))
             (todo "" ((org-agenda-overriding-header "")
                       (org-super-agenda-groups
                        '((:name "Next" :todo "NEXT" :order 1)
                          (:name "Important" :priority "A" :order 6)
                          (:name "Due Today" :deadline today :order 2)
                          (:name "Due Soon" :deadline future :order 8)
                          (:name "Overdue" :deadline past :face error :order 7)
                          (:name "Inbox" :category "inbox" :order 10)
                          (:name "To read" :tag "Read" :order 30)
                          (:name "Waiting" :todo "WAIT" :order 20)
                          (:discard (:anything t))))))))

           ("a" "dashboard"
            ((agenda "" ((org-agenda-span 'week)))
             (todo "" ((org-agenda-overriding-header "")
                       (org-super-agenda-groups
                        '((:name "Now" :todo "NOW" :order 1)
                          (:name "Next" :todo "NEXT" :order 10)
                          (:name "Due Today" :deadline today :order 20)
                          (:name "Due Soon" :deadline future :order 30)
                          (:name "Overdue" :deadline past :face error :order 70)
                          (:name "Inbox"  :category "inbox" :order 80)
                          (:name "Errands" :tag ("@errand") :order 100)
                          (:discard (:anything t))))))))
           ("p" "Projects"
            ((todo "" ((org-agenda-overriding-header "All Projects")
                       (org-agenda-remove-tags 1)
                       (org-super-agenda-groups
                        '((:auto-parent t :todo "TODO")))))))

           ("h" "@home Projects"
            ((todo "" ((org-agenda-overriding-header "Personal Projects")
                       (org-agenda-remove-tags 1)
                       (org-super-agenda-groups
                        '((:discard (:not (:tag ("@home"))))
                          (:auto-parent t :tag "@home")))))))

           ("w" "@work Projects"
            ((todo "" ((org-agenda-overriding-header "Work Projects")
                       (org-agenda-remove-tags 1)
                       (org-super-agenda-groups
                        '((:discard (:not (:tag ("@work"))))
                          (:auto-parent t)))))))

           ("r" "Errands"
            ((alltodo "" ((org-agenda-overriding-header "Errands")
                          (org-super-agenda-groups
                           '((:discard (:not (:tag "@errand")))))))))

           ("i" "Inbox"
            ((alltodo "" ((org-agenda-overriding-header "Inbox")
                          (org-super-agenda-groups
                           '((:name "Inbox" :category "inbox")
                             (:discard (:anything t)))))))))))
#+END_SRC


*** org-refile
Set the refile targets to be my project, someday, and tickler files.
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-refile-targets '((org-gtd-file-name :maxlevel . 3)
                              (org-someday-file-name :level . 1)
                              (org-tickler-file-name :maxlevel . 2))
         org-refile-allow-creating-parent-nodes 'confirm))
#+END_SRC
*** org-capture
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt
   org-capture-templates `(("i" "Inbox" entry
                            (file+headline org-inbox-file-name "Tasks")
                            "* TODO %i%?\n%U")

                           ("I" "Inbox This Line" entry
                            (file+headline org-inbox-file-name "Tasks")
                            "* TODO %i%?\n%U\n%a")

                           ("t" "Tickler" entry
                            (file+headline org-tickler-file-name "Tickler")
                            "* %i%?\n%U")

                           ("T" "Tickler This Line" entry
                            (file+headline org-tickler-file-name "Tickler")
                            "* %i%?\n%U\n%a")
                           ("p"
                            "Protocol"
                            entry
                            (file+headline ,org-notes-file-name "Notes")
                            "* %? [[%:link][%:description]]\n%U\n#+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n")
                           ("L"
                            "Protocol Link"
                            entry
                            (file+headline ,org-notes-file-name "Notes")
                            "* %?[[%:link][%:description]]\n%U\n"))))
#+END_SRC
*** org archive
#+BEGIN_SRC emacs-lisp
(after! org
  (setopt org-archive-location (concat (expand-file-name "archive.org" pipboy/gtd-directory) "::")))
#+END_SRC
** Zettelkasten
This section contains the configurations enabling me to take notes using
~org-roam~. I also take notes on papers and books using ~org-roam~. I configure
bibtex related packages to be able to use my bibs generated by Zotero in
~org-roam~.
*** org-roam
It's better to read this from the environment instead.
I am moving to a pure org-roam workflow; set org-directory to be the org-roam
files also.
#+begin_src emacs-lisp
(setopt org-roam-directory pipboy/org-notes
       org-directory pipboy/org-notes)
#+end_src
*** org-ref
Most of these configurations are inspired by [[https://www.ianjones.us/org-roam-bibtex][this link]].
#+BEGIN_SRC emacs-lisp
(use-package! org-ref
  :defer
  :after org-mode
  :config
  (setopt org-ref-bibliography-notes (concat pipboy/org-notes "/bibnotes.org") ;; TODO make this more explicit
         org-ref-notes-directory pipboy/org-notes
         org-ref-bibliography-files pipboy/bibtex-files
         reftex-default-bibliography pipboy/bibtex-files
         org-ref-default-bibliography pipboy/bibtex-files
         org-ref-pdf-directory pipboy/pdf-directory
         org-ref-completion-library 'org-ref-ivy-cite
         org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex
         org-ref-note-title-format "* TODO %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :NOTER_DOCUMENT: %F\n :ROAM_KEY: cite:%k\n  :AUTHOR: %9a\n  :JOURNAL: %j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n :END:\n\n"
         org-ref-notes-function 'orb-edit-notes))
;; TODO Rewrite title formats using the (concat ...) function
#+END_SRC

See examples in[[*helm-bibtex][ helm-bibtex]] section.
*** helm-bibtex & ivy-bibtex
#+BEGIN_SRC emacs-lisp
(setopt bibtex-completion-notes-path pipboy/org-notes
       bibtex-completion-bibliography pipboy/bibtex-files
       bibtex-completion-pdf-field "file"
       bibtex-completion-notes-template-multiple-files (concat
                                                        "#+TITLE: ${title}\n"
                                                        "#+ROAM_KEY: cite:${=key=}\n"
                                                        "* TODO Notes\n"
                                                        ":PROPERTIES:\n"
                                                        ":Custom_ID: ${=key=}\n"
                                                        ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
                                                        ":AUTHOR: ${author-abbrev}\n"
                                                        ":JOURNAL: ${journaltitle}\n"
                                                        ":DATE: ${date}\n"
                                                        ":YEAR: ${year}\n"
                                                        ":DOI: ${doi}\n"
                                                        ":URL: ${url}\n"
                                                        ":END:\n\n"))
#+END_SRC

*** org-noter
I use org-noter to take notes on PDF and EPUB documents.
#+BEGIN_SRC emacs-lisp
(setopt org-noter-notes-search-path (list pipboy/org-notes)
       org-noter-notes-window-location 'horizontal-split)
#+END_SRC
**** org-pdftools
#+BEGIN_SRC emacs-lisp
(use-package! org-pdftools
  :defer
  :after org-mode
  :hook
  (org-mode . org-pdftools-setup-link))
#+END_SRC
**** org-noter-pdftools
#+BEGIN_SRC emacs-lisp
(use-package! org-noter-pdftools
  :after org-noter
  :defer
  :config
  ;; Add a function to ensure precise note is inserted
  (defun org-noter-pdftools-insert-precise-note (&optional toggle-no-questions)
    (interactive "P")
    (org-noter--with-valid-session
     (let ((org-noter-insert-note-no-questions (if toggle-no-questions
                                                   (not org-noter-insert-note-no-questions)
                                                 org-noter-insert-note-no-questions))
           (org-pdftools-use-isearch-link t)
           (org-pdftools-use-freestyle-annot t))
       (org-noter-insert-note (org-noter--get-precise-info)))))

  ;; fix https://github.com/weirdNox/org-noter/pull/93/commits/f8349ae7575e599f375de1be6be2d0d5de4e6cbf
  (defun org-noter-set-start-location (&optional arg)
    "When opening a session with this document, go to the current location.
With a prefix ARG, remove start location."
    (interactive "P")
    (org-noter--with-valid-session
     (let ((inhibit-read-only t)
           (ast (org-noter--parse-root))
           (location (org-noter--doc-approx-location (when (called-interactively-p 'any) 'interactive))))
       (with-current-buffer (org-noter--session-notes-buffer session)
         (org-with-wide-buffer
          (goto-char (org-element-property :begin ast))
          (if arg
              (org-entry-delete nil org-noter-property-note-location)
            (org-entry-put nil org-noter-property-note-location
                           (org-noter--pretty-print-location location))))))))
  (after! pdf-annot
    (add-hook 'pdf-annot-activate-handler-functions #'org-noter-pdftools-jump-to-note)))
#+END_SRC
*** org-roam-bibtex
~org-roam-bibtex~ is a library which offers a tighter integration between
~org-roam~, ~helm-bibtex~, and ~org-ref~.

#+BEGIN_SRC emacs-lisp
(use-package! org-roam-bibtex
  :defer
  :after org-roam
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :config
  (setq orb-preformat-keywords
        '("=key=" "title" "url" "file" "author-or-editor" "keywords"))
  (setq orb-templates
        '(("r" "ref" plain (function org-roam-capture--get-point)
           ""
           :file-name "${slug}"
           :head "#+TITLE: ${=key=}: ${title}\n#+ROAM_KEY: ${ref}
- tags ::
- keywords :: ${keywords}
\n* ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :URL: ${url}\n  :AUTHOR: ${author-or-editor}\n  :NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n  :NOTER_PAGE: \n  :END:\n\n"
           :unnarrowed t))))
#+END_SRC

*** deft
**** deft user interface
#+BEGIN_SRC emacs-lisp
(defun my-deft/strip-quotes (str)
  (cond ((string-match "\"\\(.+\\)\"" str) (match-string 1 str))
        ((string-match "'\\(.+\\)'" str) (match-string 1 str))
        (t str)))

(defun my-deft/parse-title-from-front-matter-data (str)
  (if (string-match "^title: \\(.+\\)" str)
      (let* ((title-text (my-deft/strip-quotes (match-string 1 str)))
             (is-draft (string-match "^draft: true" str)))
        (concat (if is-draft "[DRAFT] " "") title-text))))

(defun my-deft/deft-file-relative-directory (filename)
  (file-name-directory (file-relative-name filename deft-directory)))

(defun my-deft/title-prefix-from-file-name (filename)
  (let ((reldir (my-deft/deft-file-relative-directory filename)))
    (if reldir
        (concat (directory-file-name reldir) " > "))))

(defun my-deft/parse-title-with-directory-prepended (orig &rest args)
  (let ((str (nth 1 args))
        (filename (car args)))
    (concat
      (my-deft/title-prefix-from-file-name filename)
      (let ((nondir (file-name-nondirectory filename)))
        (if (or (string-prefix-p "README" nondir)
                (string-suffix-p ".txt" filename))
            nondir
          (if (string-prefix-p "---\n" str)
              (my-deft/parse-title-from-front-matter-data
               (car (split-string (substring str 4) "\n---\n")))
            (apply orig args)))))))

(provide 'my-deft-title)
(require 'my-deft-title)
(advice-add 'deft-parse-title :around #'my-deft/parse-title-with-directory-prepended)
#+END_SRC
**** deft directory
I use deft to search the notes I take using org roam.
#+begin_src emacs-lisp
(setopt deft-directory pipboy/org-notes
       deft-recursive t)
#+end_src
** Enable minor modes
  #+begin_src emacs-lisp
  (add-hook! 'org-mode-hook #'auto-fill-mode)
  #+end_src
** CV & Resume
*** org-export functions
#+begin_src emacs-lisp
(defun pipboy/org-export-altacv ()
  "export buffer to altacv resume"
  (interactive)
  (let ((outfile (org-export-output-file-name ".tex")))
    (org-export-to-file 'altacv outfile)
    (org-latex-compile outfile)))
#+end_src
*** Keybindings
#+begin_src emacs-lisp
(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("o" . "org")
        :desc "org export altacv resume" "r" #'pipboy/org-export-altacv)))
#+end_src

#+RESULTS:
: pipboy/org-export-altacv

*** Export Backends
#+begin_src emacs-lisp
(use-package! ox-moderncv :after org)
(use-package! ox-altacv :after org)
#+end_src

** org-export
*** LaTex
+ Enable bibtex compilation
+ Set log files to intermediate files generated by the exporter so org-export
  delete these after exporting
#+BEGIN_SRC emacs-lisp
(setq org-latex-pdf-process
      '("%latex -interaction nonstopmode -output-directory %o %f"
        "bibtex %b"
        "%latex -interaction nonstopmode -output-directory %o %f"
        "%latex -interaction nonstopmode -output-directory %o %f")
      org-latex-logfiles-extensions
      '("lof" "lot" "tex" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb"
        "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl"
        "pygtex" "pygstyle"))
#+END_SRC

+ [ ] Set LaTex export engine to be XeLaTex
  #+begin_src emacs-lisp
    (setq org-latex-packages-alist 'nil)
    (setq org-latex-default-packages-alist
          '(("AUTO" "inputenc"  t ("pdflatex"))
            ("T1"   "fontenc"   t ("pdflatex"))
            (""     "graphicx"  t)
            (""     "grffile"   t)
            (""     "minted"   t)
            (""     "longtable" nil)
            (""     "wrapfig"   nil)
            (""     "rotating"  nil)
            ("normalem" "ulem"  t)
            (""     "amsmath"   t)
            (""     "amssymb"   t)
            (""     "unicode-math"   t)
            (""     "mathtools"   t)
            (""     "textcomp"  t)
            (""     "capt-of"   nil)
            (""     "hyperref"  nil)))

    ;; (plist-put org-format-latex-options :scale 2.2)
    ;; (add-to-list 'org-preview-latex-process-alist '(dvixelatex :programs
    ;;                                                            ("xetex" "convert")
    ;;                                                            :description "pdf > png" :message "you need to install the programs: xetex and imagemagick." :image-input-type "pdf" :image-output-type "png" :image-size-adjust
    ;;                                                            (1.0 . 1.0)
    ;;                                                            :latex-compiler
    ;;                                                            ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
    ;;                                                            :image-converter
    ;;                                                            ("dvisvgm %f -n -b min -c %S -o %O")))

    ;; (add-to-list 'org-preview-latex-process-alist '(imagexetex :programs
    ;;                                                            ("xelatex" "convert")
    ;;                                                            :description "pdf > png" :message "you need to install the programs: xelatex and imagemagick." :image-input-type "pdf" :image-output-type "png" :image-size-adjust
    ;;                                                            (1.0 . 1.0)
    ;;                                                            :latex-compiler
    ;;                                                            ("xelatex -interaction nonstopmode -output-directory %o %f")
    ;;                                                            :image-converter
    ;;                                                            ("convert -density %D -trim -antialias %f -quality 100 %O")))
  #+end_src
** org-babel
*** Prolog
#+BEGIN_SRC emacs-lisp
(use-package! ob-prolog
  :defer
  :after org-mod)
#+END_SRC
** org-drill
#+BEGIN_SRC emacs-lisp
(after! org
  (require 'org-drill))
#+END_SRC
* LaTeX
+ Use xalatex by default
  #+BEGIN_SRC emacs-lisp
   (setq-default TeX-engine 'xetex)
  #+END_SRC
+ Always Generate PDF for TeX files
  #+BEGIN_SRC emacs-lisp
  (setq-default TeX-PDF-mode t)
  #+END_SRC
+ Use luatex in latex-preview-pate
  #+BEGIN_SRC emacs-lisp
  (setq pdf-latex-command "xetex")
  #+END_SRC
* Flycheck
+ Check syntax automatically.
  #+BEGIN_SRC emacs-lisp
  (after! flycheck
    (setq flycheck-check-syntax-automatically '(mode-enabled save idle-change)))
  #+END_SRC
+ Disable flycheck in non-file-visiting buffers (e.g., claude-code-ide diff
  review buffers) where linting is noisy and irrelevant.
  #+BEGIN_SRC emacs-lisp
  (add-hook 'flycheck-mode-hook
            (lambda ()
              (when (and (not buffer-file-name)
                         (string-prefix-p "*" (buffer-name)))
                (flycheck-mode -1))))
  #+END_SRC
* Languages
** LSP
*** Configuration
+ Set a ridiculous limit on number of file watch. This is needed for Python
  virtual environments which reside inside the project worktree.
#+begin_src emacs-lisp
(setopt lsp-file-watch-threshold 100000)
#+end_src
*** Autocompletion
#+BEGIN_SRC emacs-lisp
(after! lsp
  (setq company-minimum-prefix-length   1
        company-idle-delay              0.0
        company-tooltip-idle-delay      0.0
        lsp-eldoc-render-all            nil
        lsp-lens-enable                 t))
#+END_SRC

*** LSP UI Configurations
#+BEGIN_SRC emacs-lisp
(after! lsp-ui
  (setopt lsp-ui-doc-show-with-cursor nil
         lsp-ui-sideline-enable      t
         lsp-ui-doc-max-height       15
         lsp-ui-doc-max-width        100
         lsp-ui-doc-position         'at-point
         lsp-ui-peek-always-show     t
         lsp-ui-peek-fontify         'always)

  (set-face-attribute 'lsp-face-highlight-textual nil
                      :weight 'bold
                      :background "#0A2933"
                      :foreground "#C61C6F"))
#+END_SRC

** DAP
Doom's =tools/debugger= module now uses [[https://github.com/svaante/dape][dape]] instead of =dap-mode=. All
debugger keybindings are provided under =SPC d= by the module. No user
configuration is needed here.

** Python
*** REPL
#+begin_src emacs-lisp
(setq +python-ipython-repl-args '("-i" "--simple-prompt" "--no-color-info"))
(setq +python-jupyter-repl-args '("--simple-prompt"))
#+end_src

*** Poetry
**** Key Bindings
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("p" . "poetry")
        :desc "add poetry dependency" "d" #'poetry-add
        :desc "add poetry dev dependency" "D" #'poetry-add-dev-dep
        :desc "poetry run" "r" #'poetry-run
        :desc "poetry build" "b" #'poetry-build
        :desc "poetry install" "i" #'poetry-install
        :desc "poetry install-install" "I" #'poetry-install-install)))
#+END_SRC
*** Pyright Language Server
#+BEGIN_SRC emacs-lisp
(after! python
  (setopt lsp-pyright-venv-path (expand-file-name "~/.venv/")))
#+END_SRC
*** ~sphinx-doc~
+ Enable [[https://github.com/naiquevin/sphinx-doc.el][sphinx-doc]], which generate Python docstrings for function and methods.
+ It does not work with python type hints.
#+BEGIN_SRC emacs-lisp
(use-package! sphinx-doc
  :hook (python-mode . sphinx-doc-mode))

#+END_SRC
** Prolog
*** ~ediprolog~
+ Set the Prolog interpreter to ~swipl~.
#+BEGIN_SRC emacs-lisp
(use-package! ediprolog
  :defer
  :custom
  (ediprolog-system 'swi))
#+END_SRC
** Scala
* Just
[[https://github.com/leon-barrett/just-mode.el][just-mode]] — syntax highlighting and indentation for justfiles.
[[https://github.com/psibi/justl.el][justl]] — transient UI to list and run just recipes interactively.

| Key       | Action                                      |
|-----------+---------------------------------------------|
| =SPC j j= | Open justl buffer (e = exec, w = with args) |
| =SPC j r= | Transient popup: one key per recipe → run   |
| =SPC m j= | Open justl buffer (just-mode only)           |
| =SPC m r= | Transient popup (just-mode only)             |

#+begin_src emacs-lisp
(defun pipboy/just--assign-keys (recipes)
  "Assign unique single-char keys to RECIPES, preferring first char of name."
  (let ((used '()))
    (mapcar (lambda (r)
              (let* ((name (justl--recipe-name r))
                     (preferred (substring name 0 1))
                     (key (if (not (member preferred used))
                              preferred
                            (cl-find-if (lambda (c) (not (member c used)))
                                        (mapcar #'char-to-string
                                                (number-sequence ?a ?z))))))
                (push key used)
                (cons key r)))
            recipes)))

(defun pipboy/just-recipe-transient ()
  "Transient popup of just recipes for the current project."
  (interactive)
  (require 'justl)
  (let* ((justfile (justl--find-justfile default-directory)))
    (unless justfile (user-error "No justfile found in %s" default-directory))
    (let* ((recipes  (justl--get-recipes justfile))
           (keyed    (pipboy/just--assign-keys recipes))
           (suffixes (mapcar
                      (lambda (pair)
                        (let* ((key    (car pair))
                               (recipe (cdr pair))
                               (name   (justl--recipe-name recipe))
                               (desc   (or (justl--recipe-desc recipe) name)))
                          `(,key ,desc
                                 (lambda ()
                                   (interactive)
                                   (justl--exec
                                    justl-executable ,name
                                    (append (transient-args 'justl-help-popup)
                                            (list ,name)))))))
                      keyed)))
      (eval `(transient-define-prefix pipboy/just-recipes-menu ()
               "Run just recipe"
               [["Recipes" ,@suffixes]])
            t)
      (pipboy/just-recipes-menu))))

(map! :leader
      :desc "just" "j" nil
      :desc "justl"    "j j" #'justl
      :desc "recipes"  "j r" #'pipboy/just-recipe-transient)

(use-package! just-mode
  :defer t
  :config
  (map! :map just-mode-map
        :localleader
        "j" #'justl
        "r" #'pipboy/just-recipe-transient))

(use-package! justl
  :defer t
  :config
  (setq justl-executable "just")
  (evil-set-initial-state 'justl-mode 'emacs))
#+end_src

* AI & Assistant
Three layers of AI tooling, each serving a different purpose:

| Tool            | Purpose                                  | Entry point          |
|-----------------+------------------------------------------+----------------------|
| gptel (LLM)     | Chat, explain, rewrite — multi-backend   | =SPC o l=            |
| Claude Code IDE | Agentic CLI: edits files, runs commands  | =SPC o c=            |
| Copilot         | Inline code completion as you type       | =TAB= in prog-mode   |

** LLM (gptel)
[[https://github.com/karthink/gptel][gptel]] is the engine behind Doom's =tools/llm= module. It supports multiple
backends simultaneously — the default is used by the standard doom keybinds,
while one-shot keys send to a specific backend without changing the default.

*** Backends & API keys
Each backend reads its key from an environment variable at request time (lazy,
so a missing key only errors when you actually use that backend):

| Backend   | Env var             | Free tier? | Notes                     |
|-----------+---------------------+------------+---------------------------|
| Claude    | =ANTHROPIC_API_KEY= | No         | Default. console.anthropic.com |
| Groq      | =GROQ_API_KEY=      | Yes        | Fast inference. console.groq.com |
| Gemini    | =GEMINI_API_KEY=    | Yes        | aistudio.google.com       |
| OpenAI    | =OPENAI_API_KEY=    | No         | platform.openai.com       |

*** Keybindings (=SPC o l=)
Doom module bindings (built-in, always present):

| Key       | Action                                      |
|-----------+---------------------------------------------|
| =SPC o l l= | Open gptel chat buffer                    |
| =SPC o l s= | Send prompt/selection to *default* backend |
| =SPC o l r= | Rewrite selected region                   |
| =SPC o l e= | Explain selection (gptel-quick)           |
| =SPC o l a= | Add text/region to context                |
| =SPC o l f= | Add file to context                       |
| =SPC o l m= | gptel-menu transient (full control)       |

Custom bindings added here:

| Key       | Action                                         |
|-----------+------------------------------------------------|
| =SPC o l b= | Change *default* backend+model interactively |
| =SPC o l c= | Send one-shot → Claude (Sonnet)              |
| =SPC o l g= | Send one-shot → Groq (Llama 3.3 70B)        |
| =SPC o l n= | Send one-shot → Gemini (2.0 Flash)           |
| =SPC o l p= | Send one-shot → OpenAI (GPT-4o)              |

#+begin_src emacs-lisp
;; ── One-shot send helpers ──────────────────────────────────────────────────
;; Defined at top level so they are byte-compiled. They use dynamic binding
;; to override backend/model for a single request without touching the global default.
(defun pipboy/gptel-send-with (backend-name model)
  "Send prompt/selection to BACKEND-NAME with MODEL without changing the default."
  (let ((gptel-backend (gptel-get-backend backend-name))
        (gptel-model   model))
    (call-interactively #'gptel-send)))

(defun pipboy/gptel-send-claude ()
  "Send to Claude Sonnet (one-shot, preserves default backend)."
  (interactive) (pipboy/gptel-send-with "Claude" 'claude-sonnet-4-6))

(defun pipboy/gptel-send-groq ()
  "Send to Groq Llama 3.3 70B (one-shot)."
  (interactive) (pipboy/gptel-send-with "Groq" 'llama-3.3-70b-versatile))

(defun pipboy/gptel-send-gemini ()
  "Send to Gemini 2.0 Flash (one-shot)."
  (interactive) (pipboy/gptel-send-with "Gemini" 'gemini-2.0-flash))

(defun pipboy/gptel-send-openai ()
  "Send to OpenAI GPT-4o (one-shot)."
  (interactive) (pipboy/gptel-send-with "OpenAI" 'gpt-4o))

(defun pipboy/gptel-set-default-backend ()
  "Interactively pick a backend and model to use as the gptel default."
  (interactive)
  (let* ((backend-name (completing-read "Default backend: "
                                        (mapcar #'car gptel--backends) nil t))
         (backend (gptel-get-backend backend-name))
         (models  (cl-mapcar #'symbol-name (gptel-backend-models backend)))
         (model   (intern (completing-read
                           (format "Model [%s]: " backend-name) models nil t))))
    (setq gptel-backend backend
          gptel-model   model)
    (message "gptel default → %s / %s" backend-name model)))

(after! gptel
  ;; ── Backends ──────────────────────────────────────────────────────────
  ;; Keys are read lazily at request time via getenv, so missing keys
  ;; only error when that backend is actually used.
  (gptel-make-anthropic "Claude"
    :stream t
    :key (lambda () (getenv "ANTHROPIC_API_KEY")))

  ;; Groq is OpenAI-compatible; free tier with fast llama/mixtral inference
  (gptel-make-openai "Groq"
    :host "api.groq.com"
    :endpoint "/openai/v1/chat/completions"
    :stream t
    :key (lambda () (getenv "GROQ_API_KEY"))
    :models '(llama-3.3-70b-versatile
              llama-3.1-8b-instant
              mixtral-8x7b-32768
              gemma2-9b-it))

  (gptel-make-gemini "Gemini"
    :stream t
    :key (lambda () (getenv "GEMINI_API_KEY")))

  (gptel-make-openai "OpenAI"
    :stream t
    :key (lambda () (getenv "OPENAI_API_KEY")))

  ;; ── Default backend ───────────────────────────────────────────────────
  ;; Used by SPC o l s and the chat buffer. Change at runtime with SPC o l b.
  (setq gptel-model   'claude-sonnet-4-6
        gptel-backend (gptel-get-backend "Claude"))

  ;; ── Keybindings ───────────────────────────────────────────────────────
  (map! :leader
        :prefix "o l"
        :desc "Set default backend"  "b" #'pipboy/gptel-set-default-backend
        :desc "Send → Claude"        "c" #'pipboy/gptel-send-claude
        :desc "Send → Groq"          "g" #'pipboy/gptel-send-groq
        :desc "Send → Gemini"        "n" #'pipboy/gptel-send-gemini
        :desc "Send → OpenAI"        "p" #'pipboy/gptel-send-openai))
#+end_src

** Claude Code IDE
[[https://github.com/manzaltu/claude-code-ide.el][claude-code-ide.el]] wraps the =claude= CLI with a bidirectional MCP bridge,
giving Claude access to Emacs internals (LSP, xref, imenu, diagnostics).
This is fundamentally different from gptel — it's agentic: Claude can read
and write files, run shell commands, and make multi-step changes autonomously.

Requires the =claude= CLI in PATH (installed via =npm i -g @anthropic-ai/claude-code=)
and uses your existing Claude subscription — *no separate API key needed*.

| Key         | Action                                  |
|-------------+-----------------------------------------|
| =SPC o c c= | Open/start Claude (primary action)      |
| =SPC o c t= | Toggle window (no focus steal)          |
| =SPC o c r= | Resume previous session (=-r=)          |
| =SPC o c k= | Continue recent conversation (=-c=)     |
| =SPC o c q= | Kill session                            |
| =SPC o c l= | List/switch sessions                    |
| =SPC o c p= | Send prompt from minibuffer             |
| =SPC o c i= | Insert selection into Claude prompt     |
| =SPC o c m= | Full transient menu                     |
| =SPC o c == | Widen Claude window by 15 cols          |
| =SPC o c -= | Narrow Claude window by 15 cols         |

#+begin_src emacs-lisp
(use-package! claude-code-ide
  :defer t
  :config
  (setq claude-code-ide-terminal-backend 'vterm
        claude-code-ide-vterm-render-delay 0.08
        claude-code-ide-window-side       'right
        claude-code-ide-window-width      100
        claude-code-ide-focus-on-open     t
        claude-code-ide-use-ide-diff      t)

  (claude-code-ide-emacs-tools-setup)

  ;; Strip CLAUDECODE env var so the CLI doesn't think it's a nested session.
  ;; Belt-and-suspenders: clear from process-environment AND override via
  ;; vterm-environment (vterm's C fork may bypass the Lisp variable).
  (defadvice! pipboy/claude-unset-claudecode (fn buffer-name working-dir port continue resume session-id)
    :around #'claude-code-ide--create-terminal-session
    (let ((process-environment
           (cl-remove-if (lambda (s) (string-prefix-p "CLAUDECODE=" s))
                         process-environment))
          (vterm-environment
           (cons "CLAUDECODE="
                 (if (boundp 'vterm-environment) vterm-environment nil))))
      (funcall fn buffer-name working-dir port continue resume session-id)))

  ;; Guard against race condition: if Claude exits during the stabilization
  ;; delay, vterm kills the buffer before display code runs.
  (defadvice! pipboy/claude-guard-dead-buffer (fn buffer)
    :around #'claude-code-ide--display-buffer-in-side-window
    (if (buffer-live-p buffer)
        (funcall fn buffer)
      (message "Claude session buffer was killed before display — check *Messages* for exit details")))
  (defun pipboy/claude-wider ()
    "Widen the Claude side window by 15 columns."
    (interactive)
    (cl-incf claude-code-ide-window-width 15)
    (when-let (win (get-buffer-window (claude-code-ide--get-buffer-name)))
      (window-resize win 15 t)))

  (defun pipboy/claude-narrower ()
    "Narrow the Claude side window by 15 columns."
    (interactive)
    (cl-incf claude-code-ide-window-width -15)
    (when-let (win (get-buffer-window (claude-code-ide--get-buffer-name)))
      (window-resize win -15 t))))

;; Keybindings outside :config so they are registered at startup, not on first load
(map! :leader
      :prefix ("o c" . "claude")
      :desc "Open/start Claude"      "c" #'claude-code-ide
      :desc "Toggle window"          "t" #'claude-code-ide-toggle
      :desc "Resume session"         "r" #'claude-code-ide-resume
      :desc "Continue conversation"  "k" #'claude-code-ide-continue
      :desc "Stop session"           "q" #'claude-code-ide-stop
      :desc "List sessions"          "l" #'claude-code-ide-list-sessions
      :desc "Send prompt"            "p" #'claude-code-ide-send-prompt
      :desc "Insert selection"       "i" #'claude-code-ide-insert-at-mentioned
      :desc "Menu"                   "m" #'claude-code-ide-menu
      :desc "Widen window"           "=" #'pipboy/claude-wider
      :desc "Narrow window"          "-" #'pipboy/claude-narrower)
#+end_src

** Copilot
GitHub Copilot for inline completions. Activates automatically in
=prog-mode=. Tab accepts the full suggestion; =C-TAB= accepts word-by-word.
Requires =M-x copilot-login= on first use.

#+begin_src emacs-lisp
;; (use-package! copilot
;;   :hook (prog-mode . copilot-mode)
;;   :bind (:map copilot-completion-map
;;               ("<tab>"   . copilot-accept-completion)
;;               ("TAB"     . copilot-accept-completion)
;;               ("C-TAB"   . copilot-accept-completion-by-word)
;;               ("C-<tab>" . copilot-accept-completion-by-word)))
#+end_src
